language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

env:
  matrix:
    - BUILD_TYPE=Debug
  global:
    secure: "M8/nLpE7xETAaDTf136Tfr9ubXNROfuPp9AfxkR12pNu/ErV48mSzC7wP5b9m5oO+ZvRsqFbb9BQR3aRfvLBlqe/gySh8cFN+Xl836iIT6DCZ0wpAK8JhlJYAThRzpJAB9RPwEqSyWIlB9HT35ywkeWrhH3IIGQiG2i2EyycPGU="

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install build-essential
  - if [ "$CXX" = "g++" ]; then sudo apt-get -qq --allow-unauthenticated install gcc-4.9 g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get -qq --allow-unauthenticated install clang-3.6; export CXX="clang++-3.6" CC="clang-3.6"; fi
  - sudo rm -f /usr/lib/x86_64-linux-gnu/libpng*
  - wget ftp://ftp.simplesystems.org/pub/png//src/libpng16/libpng-1.6.17.tar.gz
  - tar xf libpng-1.6.17.tar.gz
  - cd libpng-1.6.17 && ./configure --prefix=/usr --disable-dependency-tracking && make && sudo make install
  - cd ..
  - wget http://taglib.github.io/releases/taglib-1.9.1.tar.gz
  - tar xf taglib-1.9.1.tar.gz
  - cd taglib-1.9.1
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX:PATH=/usr .
  - make -j4 && sudo make install
  - cd ..
  - wget http://sourceforge.net/projects/pupnp/files/pupnp/libUPnP%201.6.19/libupnp-1.6.19.tar.bz2
  - tar xf libupnp-1.6.19.tar.bz2
  - cd libupnp-1.6.19 && ./configure --disable-dependency-tracking --prefix=/usr --disable-shared --disable-samples --disable-blocking-tcp-connections && make -j4 && sudo make install
  - cd ..

script:
  - echo "No work needed"

addons:
  coverity_scan:
    project:
      name: "dirkvdb/doozy"
      description: "Build submitted via Travis CI"
    notification_email: dirk.vdb@gmail.com
    build_command_prepend: "git submodule update --init --recursive; cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
    build_command: "make -j4"
    branch_pattern: coverity_scan
