# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpccall.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpccall.proto',
  package='doozy.proto',
  serialized_pb='\n\rrpccall.proto\x12\x0b\x64oozy.proto\">\n\nRPCRequest\x12\x0f\n\x07service\x18\x01 \x02(\t\x12\x0e\n\x06method\x18\x02 \x02(\t\x12\x0f\n\x07payload\x18\x03 \x02(\x0c\"B\n\x0bRPCResponse\x12\x10\n\x08protobuf\x18\x01 \x02(\x0c\x12\x12\n\nerror_code\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x06\n\x04Void')




_RPCREQUEST = _descriptor.Descriptor(
  name='RPCRequest',
  full_name='doozy.proto.RPCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='doozy.proto.RPCRequest.service', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='doozy.proto.RPCRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='doozy.proto.RPCRequest.payload', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=92,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RPCResponse',
  full_name='doozy.proto.RPCResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protobuf', full_name='doozy.proto.RPCResponse.protobuf', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='doozy.proto.RPCResponse.error_code', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='doozy.proto.RPCResponse.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=160,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='doozy.proto.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['RPCRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RPCResponse'] = _RPCRESPONSE
DESCRIPTOR.message_types_by_name['Void'] = _VOID

class RPCRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCREQUEST

  # @@protoc_insertion_point(class_scope:doozy.proto.RPCRequest)

class RPCResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCRESPONSE

  # @@protoc_insertion_point(class_scope:doozy.proto.RPCResponse)

class Void(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOID

  # @@protoc_insertion_point(class_scope:doozy.proto.Void)


# @@protoc_insertion_point(module_scope)
