# this one is important
SET(CMAKE_SYSTEM_NAME Windows)

SET(LIBTYPE STATIC)
SET(HOST x86_64-w64-mingw32)
SET(CROSS x86_64-w64-mingw32-)

SET(CMAKE_C_COMPILER ${CROSS}gcc)
SET(CMAKE_AR ${CROSS}gcc-ar)
SET(CMAKE_RC_COMPILER ${CROSS}windres)

#SET(CMAKE_SYSTEM_PROGRAM_PATH /c/msys64/mingw64/x86_64-w64-mingw32/bin)
SET(CMAKE_SYSROOT /c/msys64/mingw64/x86_64-w64-mingw32)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)