/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "controlpoint_constants.h"

namespace doozy { namespace rpc {

const controlpointConstants g_controlpoint_constants;

controlpointConstants::controlpointConstants() {
}

}} // namespace

