/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef controlpoint_CONSTANTS_H
#define controlpoint_CONSTANTS_H

#include "controlpoint_types.h"

namespace doozy { namespace rpc {

class controlpointConstants {
 public:
  controlpointConstants();

};

extern const controlpointConstants g_controlpoint_constants;

}} // namespace

#endif
