// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ControlPoint.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::doozy::rpc;

class ControlPointHandler : virtual public ControlPointIf {
 public:
  ControlPointHandler() {
    // Your initialization goes here
  }

  void GetRenderers(DeviceResponse& _return) {
    // Your implementation goes here
    printf("GetRenderers\n");
  }

  void GetServers(DeviceResponse& _return) {
    // Your implementation goes here
    printf("GetServers\n");
  }

  void Browse(BrowseResponse& _return, const BrowseRequest& req) {
    // Your implementation goes here
    printf("Browse\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ControlPointHandler> handler(new ControlPointHandler());
  shared_ptr<TProcessor> processor(new ControlPointProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

